spring.application.name=library


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}



spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}

server.port=8080
server.ssl.key-store=${SERVER_SSL_KEYSTORE}
server.ssl.key-store-password=${SERVER_SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=${SERVER_SSL_KEYSTORE_TYPE}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS}

# Log security events
logging.level.org.springframework.security=DEBUG